# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Test Builds

on:
  push:
    branches: [ "main", "v0_8" ]
  pull_request:
    types: [ "opened", "synchronize", "edited" ]

permissions:
  contents: read

jobs:
  test-osx:
    name: 'Build (OSX)'
    strategy:
      fail-fast: false
      matrix:
        build: [debug, release]
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install compiler
      uses: dlang-community/setup-dlang@v2
      with:
        compiler: ldc-beta

    - name: 'Build (OSX, ${{ matrix.build }}, universal)' 
      run: |
        dub build --build=${{ matrix.build }} --arch=arm64-apple-darwin
        dub build --build=${{ matrix.build }} --arch=x86_64-apple-darwin
  
  test-linux:
    name: 'Build (Linux)'
    strategy:
      fail-fast: false
      matrix:
        build: [debug, release]
        arch: [x86_64, aarch64, linux-arm]
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install compiler
      uses: dlang-community/setup-dlang@v2
      with:
        compiler: ldc-beta

    - name: 'Build ${{ matrix.os }}-${{ matrix.build }} (${{ matrix.arch }})' 
      run: |
        dub build --build=${{ matrix.build }} --arch=${{ matrix.arch }}
  
  test-windows:
    name: 'Build (Linux)'
    strategy:
      fail-fast: false
      matrix:
        build: [debug, release]
    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install compiler
      uses: dlang-community/setup-dlang@v2
      with:
        compiler: ldc-beta

    - name: 'Build ${{ matrix.os }}-${{ matrix.build }} (${{ matrix.arch }})' 
      run: |
        dub build --build=${{ matrix.build }} --arch=${{ matrix.arch }}